ActionResultsInMVC/Models/Employee.cs
namespace ActionResultsInMVC.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Job { get; set; }
        public double Salary { get; set; }
        public bool Status { get; set; }
    }
}

ActionResultsInMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ActionResultsInMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ActionResultsInMVC/Controllers/ResultsController.cs
using ActionResultsInMVC.Models;
using System;
using System.Collections.Generic;
using System.Text;
using System.Web.Mvc;
using WebGrease;

namespace ActionResultsInMVC.Controllers
{
    public class ResultsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
       public JsonResult GetEmployees()
        {
            Employee e1 = new Employee { Id = 101, Name = "Scott", Job = "CEO", Salary = 25000, Status = true };
            Employee e2 = new Employee { Id = 102, Name = "Smith", Job = "President", Salary = 22000, Status = true };
            Employee e3 = new Employee { Id = 103, Name = "Parker", Job = "Manager", Salary = 18000, Status = true };
            Employee e4 = new Employee { Id = 104, Name = "John", Job = "Salesman", Salary = 10000, Status = true };
            Employee e5 = new Employee { Id = 105, Name = "David", Job = "Clerk", Salary = 5000, Status = true };
            Employee e6 = new Employee { Id = 106, Name = "Maria", Job = "Analyst", Salary = 12000, Status = true };
            List<Employee> Emps = new List<Employee> { e1, e2, e3, e4, e5, e6 };
            return Json(Emps, JsonRequestBehavior.AllowGet);
        }
        public FileResult DownloadPdf()
        {
            return File("~/Downloads/2024062773 (1).pdf", "application/pdf");
        }
        public FileResult DownloadWord()
        {
            return File("~/Downloads/DownloadWord.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        }
        public RedirectResult OpenFaceBook()
        {
            return Redirect("https://facebook.com");
        }
        public RedirectResult OpenTwitter()
        {
            return Redirect("https://twitter.com");
        }
        public string SendDate1()
        {
            return "Current Date: " + DateTime.Now;
        }
        public ActionResult SendDate2()   // ActionResult or ContentResult as well
        {
            return Content("Current Date: " + DateTime.Now.ToString());
        }
        public string SayHello1()
        {
            return "नमस्ते आप कैसे हैं";
        }
        public ContentResult SayHello2()
        {
            return Content("नमस्ते आप कैसे हैं", "text/plain", Encoding.Unicode);
        }
        public JavaScriptResult AlertUser()
        {
            return JavaScript("alert('Hello, how are you.');");
        }
        public void ReturnEmpty1()
        {
            string str = ("Hello World").ToUpper();
        }
        public EmptyResult ReturnEmpty2()
        {
            return new EmptyResult();
        }
    }
}

ActionResultsInMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

ActionResultsInMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

ActionResultsInMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

ActionResultsInMVC/Views/Results/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index Page</h2>

<h2>MVC Action Results</h2>
<ol>
    <li>@Html.ActionLink("Json Result", "GetEmployees")</li>
    <li>@Html.ActionLink("Download Pdf", "DownloadPdf", null, new { target = "_blank" })</li>
    <li>@Html.ActionLink("Download Word", "DownloadWord")</li>
    <li>@Html.ActionLink("Facebook", "OpenFaceBook", null, new { target = "_blank" })</li>
    <li>@Html.ActionLink("Twitter", "OpenTwitter", null, new { target = "_blank" })</li>
    <li>@Html.ActionLink("Today’s date returned as ContentResult", "SendDate1")</li>
    <li>@Html.ActionLink("Today’s date returned as String", "SendDate2")</li>
    <li>@Html.ActionLink("नमस्ते बोलो returned as String", "SayHello1")</li>
    <li>@Html.ActionLink("नमस्ते बोलो returned as ContentResult", "SayHello2")</li>
    <li>@Html.ActionLink("Javascript Alert", "AlertUser")</li>
    <li>@Html.ActionLink("Empty Result", "ReturnEmpty1")</li>
    <li>@Html.ActionLink("Void Result", "ReturnEmpty2")</li>
</ol>

ActionResultsInMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Action Results", "Index", "Results", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>